### ISSUE TITLE
Not being enslaved

### ISSUE THREAD

**Issue by G1NG3RJ0HN** [MinLL/SDPlus#262]
I've tried getting killed by multiple factions, enabling/disabling specific things with daymoyl, but every time I get killed, I just am woken up by a random stranger and need to "recover my gear"

**Comment by SkyrimLL** [comment]
This usually happens when SD doesn't initialize well for some reason.

Check the logs. 
If you see many errors about Player alias not being of the right type, you will probably have to disable SD, run a save game cleaner and re-install SD.

This can happen if you start a new game with SD next to many script intensive mods.
