### ISSUE TITLE
Not being enslaved

### ISSUE THREAD

**Issue by xXTheMoomanXx** [MinLL/SDPlus#285]
Whenever i blackout it just gives me the "getting your gear back" quest and i cant get enslaved. Ive tried reinstalling nothing is working.

**Comment by SkyrimLL** [comment]
That means the quest did not initialize correctly.

Usually, it is caused by starting Skyrim with too many script heavy mods initializing at the same time.

Try starting a new game and enable mods in waves.
First enable non sexlab mods, save and quit.
Then enable Death Alternative, save and quit.
Then enable SexLab by itself, save and quit.
Finally enable other SexLab mods (including SD), save and quit.

This will give time for scripts to detect their requirements and initialize properly.

See this page for details: http://www.loverslab.com/blog/60/entry-1138-reducing-issues-when-starting-a-new-game/
