### ISSUE TITLE
"Trade and Barter - HearthFire" breaks Dialogue and Blacksmith quest

### ISSUE THREAD

**Issue by SkyrimLL** [MinLL/SDPlus#301]
@MalaVelve - "I have discovered a mod that, if activated, will interfere with vanilla quests and your smithing quest.  In paticular when following Hadvar to Riverwood to See his uncle, Hadvar will take off running and not go to see his uncle.  The Mod is called Trade and Barter - HearthFire. This mod is part of STEP but is recommended to not activate it.  I didn't know why till I discovered the behavior was due to this mod.  (The esp adds good changes so that is why it is included in STEP.) Just a heads up."

**Comment by ContentConsumer** [comment]
I have not noticed this problem, just tested several times. Also:

@MallaVelve - "I have since discovered that I must retract this statement.  Honestly i tested this 6 times and every time it was the same.  Now I play with it off and I had it happen 1 time.  In the last 3 play starts.   Really sorry...thought the testing was pretty solid.  Skyrim can be so fickle."

**Comment by SkyrimLL** [comment]
Looks like that wasn't an issue after all - closing for now.
